#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

#set -e

#if [ -z "$OPENSHIFT_POSTGRESQL_DB_HOST" ]
#then
#echo 1>&2
#    echo "Could not find mysql database. Please run:" 1>&2
#    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c postgresql-8.4" 1>&2
#    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
#    echo 1>&2
#fi

#if [ -z "$OPENSHIFT_POSTGRESQL_DB_HOST" ]
#then
#    exit 5
#fi
 

# Confirm database exists, if not create it
#if ! psql -c "select * from posts;" "$OPENSHIFT_APP_NAME" > /dev/null 2>&1
#then
#    echo
#    echo "Database schema not found, importing 'cake.sql' schema."
#    echo
#    psql -a -f "$OPENSHIFT_REPO_DIR/.openshift/action_hooks/cake.sql" "$OPENSHIFT_APP_NAME"
#    echo
#    echo "done."
#else
#    echo "Database found, skipping import."
#fi
